-- Sample Data para sa inspection_images table
INSERT INTO inspection_images (
    vessel_id,
    inspection_id,
    image_name,
    image_data,
    image_mime_type,
    image_size,
    inspection_type,
    inspection_location,
    inspector_name,
    remarks,
    detection_status,
    detection_confidence,
    is_active,
    inspection_date,
    created_at,
    updated_at
) VALUES
(
    1,
    'INSP-2024-001',
    'hull_inspection_001.jpg',
    'base64encodedimagedata==',
    'image/jpeg',
    204800,
    'Hull Inspection',
    'Port Side - Bow',
    'Juan dela Cruz',
    'Minor corrosion detected on port side hull.',
    'detected',
    85.50,
    true,
    '2024-01-15 08:30:00',
    NOW(),
    NOW()
),
(
    1,
    'INSP-2024-001',
    'deck_inspection_002.jpg',
    'base64encodedimagedata==',
    'image/jpeg',
    153600,
    'Deck Inspection',
    'Main Deck - Midship',
    'Maria Santos',
    'Surface rust observed near anchor chain locker.',
    'detected',
    92.00,
    true,
    '2024-01-15 09:00:00',
    NOW(),
    NOW()
),
(
    2,
    'INSP-2024-002',
    'engine_room_003.jpg',
    'base64encodedimagedata==',
    'image/png',
    512000,
    'Engine Room Inspection',
    'Engine Room - Lower Level',
    'Pedro Reyes',
    'No anomalies found. All systems operational.',
    'clear',
    97.25,
    true,
    '2024-02-10 10:00:00',
    NOW(),
    NOW()
),
(
    2,
    'INSP-2024-002',
    'propeller_004.jpg',
    'base64encodedimagedata==',
    'image/jpeg',
    307200,
    'Underwater Inspection',
    'Stern - Propeller Area',
    'Pedro Reyes',
    'Slight barnacle growth on propeller blades.',
    'detected',
    78.75,
    true,
    '2024-02-10 11:30:00',
    NOW(),
    NOW()
),
(
    3,
    'INSP-2024-003',
    'ballast_tank_005.jpg',
    'base64encodedimagedata==',
    'image/jpeg',
    409600,
    'Ballast Tank Inspection',
    'Ballast Tank No. 3',
    'Ana Lim',
    'Coating breakdown observed. Recommend recoating.',
    'detected',
    88.00,
    false,
    '2024-03-05 07:45:00',
    NOW(),
    NOW()
);
